name: Render CV

on: push

jobs:
  render_cv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Render PDF
        uses: docker://pandoc/latex:latest
        with:
          args: --from=markdown+yaml_metadata_block --template=cv-template.latex --output=linus-borjesson-cv.pdf linus-borjesson-cv.md

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: linus-borjesson-cv.pdf
