name: Render CV

on: push

jobs:
  render_cv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Render PDF
        uses: docker://pandoc/latex:latest
        with:
          args: --from=markdown+yaml_metadata_block --template=cv-template.latex --output=linus-borjesson-cv.pdf linus-borjesson-cv.md

      - name: Stamp release
        id: stamp
        run: echo "tag=$(date +'%Y-%m-%d-%H%M%S')" >> "$GITHUB_OUTPUT"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.stamp.outputs.tag }}
          tag_name: ${{ steps.stamp.outputs.tag }}
          files: |
            linus-borjesson-cv.pdf
